name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Hub Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag darkpanda08/qrcode-api:$(date +%s)
    - name: Push to Docker Hub
      run: docker push ${{secrets.DOCKER_USER}}/qrcode-api
