name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Check out Repo
      uses: actions/checkout@v2

    - name: Docker Hub Login
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USER }}/qrcode-api:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}